### ISSUE TITLE
exampleFunctional

### ISSUE THREAD

**Issue by ahy95** [mgp25/Telegram-Bot-API#2]
Hi I wants send simple massage(for example hi) to my but i dont know how use from my `HTTP API(102***462:AAFlpWrP-p6euiLfbc0C93LMW***OBLxFxU`) so in below(part1) i send my exampleFunctional.php pleas check what is my problem? and my `error_log` in cpanel show fatel error that i send you in part 2 

part1:

``` php
<?php

require '../src/Telegram.php';

//                                       //
///////// CONFIG YOUR BOT'S TOKEN /////////
$token = "102***462:AAFlpWrP-p6euiLfbc0C93LMW***OBLxFxU";
$tg = new telegramBot($token);

$chat_id      = 'alihyazdi';
$guessed      = false;
$sendQuestion = false;


// Custom keyboard
$customKeyboard = [
    ['7', '8', '9'],
    ['4', '5', '6'],
    ['1', '2', '3'],
         ['0']
];
$reply_markup = $tg->replyKeyboardMarkup($customKeyboard, true, true);

do
{
  // Get updates the bot has received
  // Offset to confirm previous updates
  $updates = $tg->pollUpdates($offset);
  if ($updates['ok'])
  {
    foreach($updates['result'] as $data)
    {
        if (is_null($chat_id))
          $chat_id = $data['message']['chat']['id'];

        if (!$sendQuestion)
        {
          // sends an action 'typing'
          $tg->sendChatAction($chat_id, 'typing');

          // send message with a custom reply markup
          $tg->sendMessage($chat_id, 'Guess the number', false, null, $reply_markup);
          $sendQuestion = true;
        }

        if (($data['message']['text']) == 5)
        {
          $tg->sendChatAction($chat_id, 'typing');
          $tg->sendMessage($chat_id, 'You did it! :)');

          $tg->sendChatAction($chat_id, 'upload_photo');
          $tg->sendPhoto($chat_id, 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/718smiley.png/220px-718smiley.png');
          $guessed = true;
        }
        else
          $tg->sendMessage($chat_id, 'Wrong number :/ try again', false, null, $reply_markup);
    }
    $offset = $updates['result'][count($updates['result']) - 1]['update_id'] + 1;
  }
}
while(!$guessed);
$offset  = $updates['result'][count($updates['result']) - 1]['update_id'] + 1;
$updates = $tg->pollUpdates($offset);
```

part2:

```
[06-Aug-2015 01:00:24 UTC] PHP Fatal error:  Uncaught exception 'TelegramException' with message 'Required "token" key not supplied' in /home/hosseiny/public_html/telegram/src/Telegram.php:15
Stack trace:
#0 /home/hosseiny/public_html/telegram/examples/exampleFunctional.php(7): telegramBot->__construct(NULL)
#1 {main}
  thrown in /home/hosseiny/public_html/telegram/src/Telegram.php on line 15
[06-Aug-2015 01:00:27 UTC] PHP Fatal error:  Uncaught exception 'TelegramException' with message 'Required "token" key not supplied' in /home/hosseiny/public_html/telegram/src/Telegram.php:15
Stack trace:
#0 /home/hosseiny/public_html/telegram/examples/exampleFunctional.php(7): telegramBot->__construct(NULL)
#1 {main}
  thrown in /home/hosseiny/public_html/telegram/src/Telegram.php on line 15
```

**Comment by mgp25** [comment]
@ahy95 you only need to set the token:

``` php
$token = "102***462:AAFlpWrP-p6euiLfbc0C93LMW***OBLxFxU";
```

Don't touch this value:

``` php
$chat_id      = null;
```

Regards

**Comment by ahy95** [comment]
thanks
But how i can send massage to my friend user???

**Comment by mgp25** [comment]
@ahy95 in that case, you need the `chat_id`, your friend has to chat with your bot, and using `pollUpdates` you will get that `chat_id`

**Comment by ahy95** [comment]
so for example in `exampleFunctional.php` how i can use from `pollUpdates`? because you said i don't touch
`$chat_id      = null;`
 and you said i only need to set the token but i don't  know yet via `exampleFunctional.php` to whom I send?

**Comment by mgp25** [comment]
@ahy95 oks, it seems you havent read the [wiki](https://github.com/mgp25/Telegram-Bot-API/wiki) right? Everything is explained there... 

sigh... anyway, in this example only set your token and leave the script running and chat with your bot, and you will see how it works the `exampleFunctional.php` script?

Have you tried that?

If you need more help send me better an email

Regards

**Comment by ahy95** [comment]
http://www.hosseinyazdi.ir/telegram/examples/exampleFunctional.php
I set the token but nothing happens
i read wiki but is not complete i think in your whatsapp scrip you have a better wiki and issue
what is your suggestion?

**Comment by mgp25** [comment]
@ahy95 run it via ssh/telnet or whatever or using terminal/cmd, and leave the script running, don't run it via http (browser)
